import CHM from './CHM.png';
import CMS from './CMS.png';
import MYM from './MYM.png';
import YKH from './YKH.png';

export const team = [
  {
    id: 0,
    picture: MYM,
    name: '문윤미',
    gitId: 'do66i',
    link: 'https://github.com/Do66i',
    position: 'Front-End',
  },
  {
    id: 1,
    picture: YKH,
    name: '윤기혁',
    gitId: 'Yquick',
    link: 'https://github.com/Yquick',
    position: 'Front-End',
  },
  {
    id: 2,
    picture: CHM,
    name: '최현민',
    gitId: 'HyunminChoi1997',
    link: 'https://github.com/HyunminChoi1997',
    position: 'Back-End',
  },
  {
    id: 3,
    picture: CMS,
    name: '최만선',
    gitId: 'full-fish',
    link: 'https://github.com/full-fish',
    position: 'Back-End',
  },
  {
    id: 4,
    picture: MYM,
    name: '문윤미',
    gitId: 'do66i',
    link: 'https://github.com/Do66i',
    position: 'Front-End',
  },
  {
    id: 5,
    picture: YKH,
    name: '윤기혁',
    gitId: 'Yquick',
    link: 'https://github.com/Yquick',
    position: 'Front-End',
  },
  {
    id: 6,
    picture: CHM,
    name: '최현민',
    gitId: 'HyunminChoi1997',
    link: 'https://github.com/HyunminChoi1997',
    position: 'Back-End',
  },
  {
    id: 7,
    picture: CMS,
    name: '최만선',
    gitId: 'full-fish',
    link: 'https://github.com/full-fish',
    position: 'Back-End',
  },
  {
    id: 8,
    picture: MYM,
    name: '문윤미',
    gitId: 'do66i',
    link: 'https://github.com/Do66i',
    position: 'Front-End',
  },
  {
    id: 9,
    picture: YKH,
    name: '윤기혁',
    gitId: 'Yquick',
    link: 'https://github.com/Yquick',
    position: 'Front-End',
  },
  {
    id: 10,
    picture: CHM,
    name: '최현민',
    gitId: 'HyunminChoi1997',
    link: 'https://github.com/HyunminChoi1997',
    position: 'Back-End',
  },
  {
    id: 11,
    picture: CMS,
    name: '최만선',
    gitId: 'full-fish',
    link: 'https://github.com/full-fish',
    position: 'Back-End',
  },
  {
    id: 12,
    picture: MYM,
    name: '문윤미',
    gitId: 'do66i',
    link: 'https://github.com/Do66i',
    position: 'Front-End',
  },
  {
    id: 13,
    picture: YKH,
    name: '윤기혁',
    gitId: 'Yquick',
    link: 'https://github.com/Yquick',
    position: 'Front-End',
  },
  {
    id: 14,
    picture: CHM,
    name: '최현민',
    gitId: 'HyunminChoi1997',
    link: 'https://github.com/HyunminChoi1997',
    position: 'Back-End',
  },
  {
    id: 15,
    picture: CMS,
    name: '최만선',
    gitId: 'full-fish',
    link: 'https://github.com/full-fish',
    position: 'Back-End',
  },
  {
    id: 16,
    picture: MYM,
    name: '문윤미',
    gitId: 'do66i',
    link: 'https://github.com/Do66i',
    position: 'Front-End',
  },
  {
    id: 17,
    picture: YKH,
    name: '윤기혁',
    gitId: 'Yquick',
    link: 'https://github.com/Yquick',
    position: 'Front-End',
  },
  {
    id: 18,
    picture: CHM,
    name: '최현민',
    gitId: 'HyunminChoi1997',
    link: 'https://github.com/HyunminChoi1997',
    position: 'Back-End',
  },
  {
    id: 19,
    picture: CMS,
    name: '최만선',
    gitId: 'full-fish',
    link: 'https://github.com/full-fish',
    position: 'Back-End',
  },
];
